In [1]:
%load_ext autoreload
%autoreload 2

In [127]:
import itertools
import math

import numpy as np

import torch
from torch import nn
import torch.nn.functional as F


device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Session 2 – NLP Models and Training Basics (RNN)
  
In this notebook, we will dive into fundamental sequence models such as **RNNs** and **LSTMs**. We’ll also cover basic neural embeddings, training objectives, and see how to implement and train a **simple text generator** using an LSTM.


## Table of Contents

1. [Introduction and Overview](#introduction)
2. [Recurrent Neural Networks (RNNs)](#rnns)
   - [The RNN Cell](#rnn-cell)
   - [Vanishing and Exploding Gradients](#vanishing)
3. [Long Short-Term Memory (LSTM)](#lstm)
   - [Key Intuition Behind LSTM Gates](#lstm-gates)
4. [Embeddings](#embeddings)
5. [Basic Training Objectives in Language Modeling](#training-objectives)
   - [Next Token Prediction](#next-token-pred)
   - [Perplexity](#perplexity)
6. [Implementing a Simple LSTM Text Generator in PyTorch](#implementation)
   - [Data Preparation](#data-prep)
   - [Model Definition](#model-def)
   - [Training Loop](#training-loop)
   - [Generating Text](#generate-text)

Each section will be followed by one or more **Exercises** to help you practice.

# <a id="overview"></a>1. Overview and Setup

This tutorial assumes you have:

- **Basic Python** knowledge.
- A local or cloud environment (e.g., Jupyter, Colab) with **PyTorch** installed.
  - If needed, install PyTorch via `pip install torch` or follow instructions at [pytorch.org](https://pytorch.org/get-started/locally/).

No prior reading of other sessions is required; we’ll present all the essentials here.

### Quick Setup Check
```python
import torch
print("PyTorch version:", torch.__version__)
```

Ensure you see a version number (e.g., `2.0.0` or similar) printed. If you get an error, please install or update PyTorch before continuing.

- We’ll focus on **RNNs** and **LSTMs**.  
- We’ll learn **why** they are powerful for sequential data.  
- We’ll cover **basic training objectives** (like next-token prediction) for language modeling.  
- Finally, we’ll implement a small **LSTM-based text generator**.

**By the end of this session**, you should be able to:
1. Understand how an RNN cell and LSTM cell process sequential data.  
2. Implement an **LSTM** in a deep learning framework (here, PyTorch).  
3. Train and evaluate a **text-generation** model.  

In [3]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.6.0


# 2. Recurrent Neural Networks (RNNs)<a id="rnns"></a>

Recurrent Neural Networks are designed to handle **sequential data** by maintaining a hidden state that captures information about previous time steps. 

## Key Idea
At each time step $t$:
1. The RNN takes an input $x_t$ and the hidden state from the previous time step $h_{t-1}$.
2. It produces a new hidden state $h_t$.

Mathematically, a very **basic** RNN can be written as:
$$
\begin{aligned}
h_t &= \tanh(W_{hh} h_{t-1} + W_{xh} x_t + b_h) \\
y_t &= W_{hy} h_t + b_y
\end{aligned}
$$

- $h_t$ is the updated hidden state.
- $y_t$ is the output at time step $t$ (used for tasks like classification or next-token prediction).
- $W_{hh}, W_{xh}, W_{hy}$ are learned weight matrices.

**Rearrangement of Terms**

Notice that the term $W_{hh} h_{t-1} + W_{xh} x_t$ uses two matrix multiplications and an addition.
Unless compiled, these two multiplications will be performed sequentially.
We can gain a slight improvement if we concatenate $h$ and $x$, and use a single matrix multiplication by a larger weight matrix:

$$
\begin{aligned}
h_t &= \tanh(W_h H_t + b_h) \\
y_t &= W_{hy} h_t + b_y
\end{aligned}
$$

- $H_t = [h_{t-1}||x_t]$ is the concatenation of $h$ and $x$
- $W_{h} = [W_{hh}||W_{xh}]$ is the cconcatenaation of $W_{hh}, W_{xh}$


<img src="img_src/RNNs.svg"/>


## <a id="rnn-cell"></a>The RNN Cell

The **RNN cell** is the fundamental computational unit. At time step $t$:
1. **Input**: current token (often embedded) + previous hidden state.
2. **Output**: updated hidden state + optional output vector.

If you unroll this cell over time for $T$ steps, you get a **computation graph** that looks like a chain, where each link is an RNN cell.

<img src="img_src/RNN-folded.svg"/>
<img src="img_src/RNN-unfolded.svg"/>

### Exercise: Implement a Toy RNN Cell
**Goal**:  
1. Write a Python function that computes a single time-step of an RNN.  
1. Use NumPy or PyTorch (in NumPy style) to do the matrix multiplication and a `tanh` activation.  
1. Test it on a small input (e.g., input dimension of 5, hidden dimension of 3).

*(Keep it simple—focus on the concept, not a full RNN unrolled over time.)*  

In [4]:
import torch

def rnn_step(x_t, h_prev, Wxh, Whh, bh):
    """Simple RNN step

    Args:
        x_t: shape (batch_size, input_dim)
        h_prev: shape (batch_size, hidden_dim)
        Wxh: shape (input_dim, hidden_dim)
        Whh: shape (hidden_dim, hidden_dim)
        bh: shape (hidden_dim,)
    Returns:
        h_t: shape (batch_size, hidden_dim) 
    """
    weighted_h = h_prev @ Whh  # shape: (batch_size, hidden_dim)
    weighted_x = x_t @ Wxh  # shape: (batch_size, hidden_dim)
    linear_hx = weighted_h + weighted_x + bh
    nonlinear_hx = torch.tanh(linear_hx)
    return nonlinear_hx

# Tests -- we only consider shapes here
N = (1, 2, 5)  # Batch sizes
hidden_dims = (1, 2, 5)  # Hidden sizes
input_dims = (1, 2, 5)  # Input sizes

failed_cases = []
for batch_size, hdim, xdim in itertools.product(N, hidden_dims, input_dims):
    x = torch.ones(batch_size, xdim)
    h = torch.zeros(batch_size, hdim)
    Wxh = torch.ones(xdim, hdim)
    Whh = torch.ones(hdim, hdim)
    bh = torch.zeros(hdim)
    expect_shape = (batch_size, hdim)
    with torch.no_grad():
        h_next = rnn_step(x, h, Wxh, Whh, bh)
    if h_next.shape != expect_shape:
        print('x', end='')
        failed_cases.append((h_next.shape, expect_shape))
    else:
        print('.', end='')
print()
for got, expected in failed_cases:
    print(f"{expected} vs. {got}")

...........................


In [ ]:
# PyTorch implementation
class RNN(nn.Module):
    def __init__(self, data_dim, state_dim):
        super().__init__(data_dim, state_dim)

        # Define parameters to train
        self.input_linear = nn.Linear(  # Takes [x||h_prev] and produces h_next
            in_features=self.data_dim + self.state_dim,
            out_features=self.state_dim,
            bias=True)
        self.output_linear = nn.Linear(  # Takes h_next and produces y
            in_features=self.state_dim,
            out_features=self.data_dim,
            bias=True)
        self.tanh = nn.Tanh()

    def forward(self, x, h=None):
        # Concatenate x and hidden_state
        if h is None:
            h = torch.zeros(x.shape[0], self.state_dim, device=x.device, dtype=x.dtype)
        xh = torch.hstack([x, h])

        # Compute new hidden state
        xh = self.input_linear(xh)
        h_next = self.tanh(xh)

        # Compute output
        y = self.output_linear(h_next)
        return y, h_next

## <a id="vanishing"></a>Vanishing and Exploding Gradients

**Problem**: Simple RNNs often struggle with **long-term dependencies** due to **vanishing** or **exploding gradients**. That means:
- When sequences are long, the gradient that flows backward through time either becomes extremely small (**vanishes**) or extremely large (**explodes**).
- This makes training unstable or ineffective for capturing long-range context.

**Solution**: Specialized RNN variants like **LSTM** or **GRU** mitigate these issues by incorporating gating mechanisms.

### Research Note: let's invent a GRU (Gated Recurrent Unit)

**RNN** : $h_t = \phi(W_hh_{t-1} + W_xx_{t})$

* **Problem:** To compute the gradient of $h_1$ (or any early token), we need to multiply the gradients by small values in $W_h$, thus **vanishing** it.
* **Solution:** Intelligently choose the previous memory: $h_t = \phi(W_hh_{t-1} + W_xx_{t})$ or $h_t = h_{t-1}$

**RNN with no vanishing** : $h_t = \alpha\odot\hat{h}_t + (1-\alpha)\odot h_{t-1}$, where $\hat{h}_t=\phi(W_hh_{t-1} + W_xx_{t})$

* **Problem:** To compute the gradient of $h_1$ (or any early token), we need to multiply the gradients by large values in $W_h$, thus **exploding** it.
* **Solution:** Intelligently choose to set the previous memory to zero before multiplying it by the weights: $h_t = \phi(W_hh_{t-1} + W_xx_{t})$ or $h_t = \phi(W_xx_{t})$

**RNN with no explosion** : $h_t = \phi(W_h(\beta \odot h_{t-1}) + W_xx_{t})$

* **Problem:** How do we decide on the values of $\alpha$ and $\beta$?
* **Solution:** Don't! Let the data decide (learning)

$$
\begin{aligned}
h_t &= \overbrace{\alpha\odot\underbrace{\phi\left(W_h(\beta \odot h_{t-1}) + W_xx_{t}\right)}_{\text{no explosion}} + (1-\alpha)\odot h_{t-1}}^\text{no vanishing} \\
\text{where}\\
\alpha &= \sigma\left(Ah_{t-1} + Bx_t\right) &&\text{Memory Update Gate}\\
\beta &= \sigma\left(Ch_{t-1} + Dx_t\right) &&\text{Memory Reset Gate}
\end{aligned}
$$

**Congratulations**, you have just invented a **Gated Recurrent Unit** (GRU)!

*An earlier version of a gated recurrent network is [LSTM](https://en.wikipedia.org/wiki/Long_short-term_memory), which follows very similar logic for preserving the long-term context infromation.*

| Network | Complexity | Long-Term Relationship | Gradient Issues |
|---------|--------------|------|----|
| RNN (tanh) | (++) | None | (-) |
| GRU | (+) | (+)<br/>Single state | (++) |
| LSTM | (--) | (++)<br/>Separate state for long and short terms | (++) |

# <a id="lstm"></a>3. Long Short-Term Memory (LSTM)

A **Long Short-Term Memory (LSTM)** network is a type of RNN specifically designed to better capture **long-range dependencies**. It addresses the vanishing/exploding gradient problem through gates that control the flow of information.

### <a id="lstm-gates"></a>Key Intuition Behind LSTM Gates

Typical LSTM equations:

$$\begin{aligned}
f_t &= \sigma(W_f [h_{t-1}, x_t] + b_f)
&\quad(\text{Forget Gate}) \\
i_t &= \sigma(W_i [h_{t-1}, x_t] + b_i)
&\quad(\text{Input Gate}) \\
\tilde{C_t} &= \tanh(W_C [h_{t-1}, x_t] + b_C)
&\quad(\text{Candidate Values}) \\
C_t &= f_t \odot C_{t-1} + i_t \odot \tilde{C_t}
&\quad(\text{Cell State Update}) \\
o_t &= \sigma(W_o [h_{t-1}, x_t] + b_o)
&\quad(\text{Output Gate}) \\
h_t &= o_t \odot \tanh(C_t)
&\quad(\text{New Hidden State})
\end{aligned}$$

- **Forget Gate** ($f_t$): decides how much old state to keep.
- **Input Gate** ($i_t$): decides how much new information to add.
- **Candidate** ($\tilde{C_t}$): proposed update to the cell state.
- **Output Gate** ($o_t$): decides how much cell state to output as hidden state.

This gating mechanism helps **preserve gradients** across many time steps.


### Exercise: Compare RNN and GRU Outputs (or LSTM if you prefer)
1. Create a synthetic sequence of length 20.  
2. Feed it into a small **Vanilla RNN** and a small **GRU** (in PyTorch).  
3. Compare the final hidden states after feeding all time steps. Are they similar? If you vary the length from 20 to 50 to 100, how do the hidden states change?

*Hint*: This is a conceptual experiment. You can use random inputs, then measure how the hidden states drift over longer sequences. 

*Hint*: **If you really want**, you can use the utilities in the `utils.py` file to generate simple synthetic sequences (`generate_synthetic_sequences`).

*Hint*: You don't have to train the network, but if you want to you can use `utils.py` (`train_recurrent`)

In [120]:
from torch import nn

batch_size = 3
sequence_length = 10
xdim = 3
hdim = 2

x = torch.ones(sequence_length, batch_size, xdim)  # Input sequence
h = torch.zeros(1, batch_size, hdim)  # Initial hidden state / initial memory

rnn_model = nn.RNN(input_size=xdim, hidden_size=hdim, num_layers=1, batch_first=False, bidirectional=False)
gru_model = nn.GRU(input_size=xdim, hidden_size=hdim, num_layers=1, batch_first=False, bidirectional=False)
lstm_model = nn.LSTM(input_size=xdim, hidden_size=hdim, batch_first=False)

rnn_model.zero_grad()
gru_model.zero_grad()
lstm_model.zero_grad()

y_rnn, h_rnn = rnn_model(x)
y_gru, h_gru = gru_model(x)
y_lstm, (h_lstm, c_lstm) = lstm_model(x)

print(f"Hidden output shapes: {h_rnn.shape=}, {h_gru.shape=}, {h_lstm.shape=}, {c_lstm.shape=}")

# Very basic error -- just minimizing the norm of the memory
rnn_error = h_rnn.norm()
gru_error = h_gru.norm()
lstm_error = h_lstm.norm() + c_lstm.norm()

rnn_error.backward()
gru_error.backward()
lstm_error.backward()

print(f"Hidden state norms: {rnn_error:.2e}, {gru_error:.2e}, {lstm_error:.2e}")

Hidden output shapes: h_rnn.shape=torch.Size([1, 3, 2]), h_gru.shape=torch.Size([1, 3, 2]), h_lstm.shape=torch.Size([1, 3, 2]), c_lstm.shape=torch.Size([1, 3, 2])
Hidden state norms: 9.96e-01, 2.00e+00, 2.91e+00


In [121]:
rnn_model.weight_hh_l0.grad, gru_model.weight_hh_l0.grad, lstm_model.weight_hh_l0.grad

(tensor([[0.5695, 0.3378],
         [0.5443, 0.3228]]),
 tensor([[-0.0997, -0.1173],
         [ 0.0308,  0.0358],
         [ 0.0012,  0.0012],
         [ 0.0363,  0.0388],
         [ 0.3305,  0.3887],
         [ 0.0720,  0.0834]]),
 tensor([[ 0.1479, -0.1351],
         [ 0.2204, -0.1990],
         [ 0.2406, -0.2199],
         [ 0.2446, -0.2221],
         [ 0.5650, -0.5166],
         [-0.4403,  0.3976],
         [ 0.1588, -0.1445],
         [ 0.0152, -0.0163]]))

# <a id="embeddings"></a>4. Embeddings

**TODO: Embedding and Latent Space Explanation**

When dealing with text, each word or token is usually mapped to an **embedding** vector rather than a large one-hot vector.

- **Embedding Layer**: A learnable matrix that maps token indices to dense vectors of fixed dimension $d$.
- This helps the model learn **semantic relationships** between words.

For example:
- Word “hello” → index 5 → embedding vector $\mathbf{e} \in \mathbb{R}^d$.

Most frameworks (like PyTorch) provide a built-in layer, `nn.Embedding(vocab_size, embed_dim)`, that handles this.


### Exercise 3: Custom Embedding Lookup
1. Create a small vocabulary of 5 tokens.  
2. Initialize a random embedding matrix of shape $(5, d)$.  
3. Write a function that takes a token index and returns the corresponding embedding row.  
4. Compare with `nn.Embedding` in PyTorch for the same matrix initialization.


In [123]:
vocab_size = 5
embed_dim = 3
torch.manual_seed(42)

# Step 1: create a random embedding matrix
embedding_matrix = torch.randn(vocab_size, embed_dim)

def custom_embed_lookup(token_idx, embedding_matrix):
    """
    token_idx: int index (0 <= token_idx < vocab_size)
    embedding_matrix: shape (vocab_size, embed_dim)
    returns: torch.Tensor of shape (embed_dim,)
    """
    return embedding_matrix[token_idx]

# Pick a test token index
test_idx = 2
custom_vec = custom_embed_lookup(test_idx, embedding_matrix)
print("Custom lookup vector:", custom_vec)

# Step 2: Compare with nn.Embedding
embed_layer = nn.Embedding(vocab_size, embed_dim)
# Overwrite the embedding_layer's weights with our random matrix
with torch.no_grad():
    embed_layer.weight.copy_(embedding_matrix)

# Now let's see if it matches:
with torch.no_grad():
    torch_vec = embed_layer(torch.tensor([test_idx]))
print("nn.Embedding lookup vector:", torch_vec.squeeze(0))

# They should be (almost) identical
print("Difference:", (custom_vec - torch_vec.squeeze(0)).abs().sum().item())


Custom lookup vector: tensor([ 2.2082, -0.6380,  0.4617])
nn.Embedding lookup vector: tensor([ 2.2082, -0.6380,  0.4617])
Difference: 0.0


# <a id="training-objectives"></a>5. Training Objectives in Language Modeling

In language modeling, a typical goal is **next-token prediction**: given the previous tokens, predict the next one. We often use **cross-entropy loss** and measure model performance with **perplexity**.

### <a id="next-token-prediction"></a>Next Token Prediction

For a vocabulary of size $V$, the model outputs a probability distribution over the next token:
$$
P(x_t \mid x_{t-1}, x_{t-2}, \ldots, x_1)
$$
The training loss for a sequence might be:
$$
\mathcal{L} = -\sum_{t}\log P(\hat{x}_t = x_t)
$$
where $ x_t $ is the ground truth and $\hat{x}_t$ is the predicted distribution.


### <a id="perplexity"></a>Perplexity

**Perplexity (PPL)** is a common metric for language models:
$$
\text{PPL} = \exp\left(-\frac{1}{N}\sum_{t=1}^{N} \log P(x_t)\right),
$$
where $N$ is the total number of tokens in the test set. Lower PPL typically means a better language model.


### Exercise 4: Manual Cross-Entropy
- Let your model output a probability vector $[0.2, 0.3, 0.1, 0.4]$ for a 4-word vocabulary.  
- Suppose the correct label is index 3. Manually compute cross-entropy.  
- Compare with `torch.nn.functional.cross_entropy` to confirm your result.

In [129]:
import torch.nn.functional as F

probs = torch.tensor([0.2, 0.3, 0.1, 0.4])
true_label = 3  # index 3 is the correct label

# 1) Manual cross-entropy
manual_ce = -math.log(probs[true_label].item())

# 2) Using PyTorch (note that F.cross_entropy expects logits, not probabilities!)
# So we need to convert probabilities => logits with log-softmax inverse => logit = log(p_i / 1)
# But simpler is to do cross_entropy on log(prob) by building a single "batch" example:
logits = torch.log(probs).unsqueeze(0)  # shape (1, 4)
targets = torch.tensor([true_label])    # shape (1,)

ce_torch = F.nll_loss(logits, targets)  # nll_loss expects log-probabilities
# or equivalently: ce_torch = F.cross_entropy(logits, targets) if we interpret logits as log-probs

print("Manual cross-entropy:", manual_ce)
print("PyTorch cross-entropy:", ce_torch.item())


Manual cross-entropy: 0.916290716972994
PyTorch cross-entropy: 0.9162907004356384


# <a id="implementation"></a>6. Implementing a Simple LSTM Text Generator in PyTorch

Let’s build a small example that:
1. **Prepares a tiny text dataset**.
2. Splits it into input–target pairs for next-token prediction.
3. Defines and trains an LSTM-based model.
4. **Generates** text from the trained model.

### <a id="data-prep"></a>Data Preparation

In [131]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# For reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Example small text
text = "hello world hello pytorch hello world again"

# Tokenize (word-level for simplicity)
words = text.split()
vocab = list(set(words))
vocab_size = len(vocab)
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for w, i in word2idx.items()}

print("Vocabulary:", vocab)
print("Mapping (word -> idx):", word2idx)
print("Vocab size:", vocab_size)

# Convert words to indices
indices = [word2idx[w] for w in words]

# We'll choose a sequence length
seq_length = 3

# Prepare training data
input_sequences = []
target_words = []

for i in range(len(indices) - seq_length):
    input_seq = indices[i:i+seq_length]   # 3 words
    target = indices[i+seq_length]        # the 4th word is the label
    input_sequences.append(input_seq)
    target_words.append(target)

input_sequences = torch.tensor(input_sequences, dtype=torch.long)
target_words = torch.tensor(target_words, dtype=torch.long)

print("Input sequences shape:", input_sequences.shape)
print("Target words shape:", target_words.shape)

Vocabulary: ['pytorch', 'world', 'again', 'hello']
Mapping (word -> idx): {'pytorch': 0, 'world': 1, 'again': 2, 'hello': 3}
Vocab size: 4
Input sequences shape: torch.Size([4, 3])
Target words shape: torch.Size([4])


In [147]:
for seq, targ in zip(input_sequences, target_words):
    seq = seq.numpy()
    targ = targ.item()
    seq_detokenized = list(map(idx2word.get, seq))
    targ_detokenized = idx2word.get(targ)
    print(f"{seq} => {targ}")
    print(f"  {input_sequences_detokenized} => {targ_detokenized}")

[3 1 3] => 0
  ['pytorch', 'hello', 'world'] => pytorch
[1 3 0] => 3
  ['pytorch', 'hello', 'world'] => hello
[3 0 3] => 1
  ['pytorch', 'hello', 'world'] => world
[0 3 1] => 2
  ['pytorch', 'hello', 'world'] => again


### <a id="model-def"></a>Model Definition


In [149]:
class SimpleLSTM(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super(SimpleLSTM, self).__init__()
        # 1) Embedding layer
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        # 2) LSTM layer
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        # 3) Linear output layer
        self.fc = nn.Linear(hidden_dim, vocab_size)
    
    def forward(self, x):
        # x: (batch_size, seq_length)
        embedded = self.embedding(x)                # (batch_size, seq_length, embed_dim)
        lstm_out, (h_n, c_n) = self.lstm(embedded)  # (batch_size, seq_length, hidden_dim)
        final_hidden = lstm_out[:, -1, :]           # last time step
        logits = self.fc(final_hidden)              # (batch_size, vocab_size)
        return logits

### <a id="training-loop"></a>Training Loop

In [150]:
embed_dim = 8
hidden_dim = 16
learning_rate = 0.01
num_epochs = 200

model = SimpleLSTM(vocab_size, embed_dim, hidden_dim)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(num_epochs):
    model.train()
    
    optimizer.zero_grad()
    logits = model(input_sequences)  # shape: (batch_size, vocab_size)
    loss = criterion(logits, target_words)
    
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 50 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Epoch [50/200], Loss: 0.0115
Epoch [100/200], Loss: 0.0030
Epoch [150/200], Loss: 0.0018
Epoch [200/200], Loss: 0.0012


### <a id="generate-text"></a>Generating Text

We can now generate text by **sampling** the model’s predictions iteratively.

Feel free to experiment with:
- **Different seeds**.
- **Different sampling strategies** (e.g., greedy vs. top-k).  
- A **larger corpus** (like Tiny Shakespeare).

In [153]:
def generate_text(model, seed_words, num_words=5):
    model.eval()
    words_generated = seed_words[:]
    
    # Convert seed_words to indices
    current_seq = [word2idx[w] for w in seed_words]
    
    for _ in range(num_words):
        inp = torch.tensor([current_seq], dtype=torch.long)
        with torch.no_grad():
            logits = model(inp)  # shape: (1, vocab_size)
        probs = torch.softmax(logits, dim=-1).squeeze()  # shape: (vocab_size,)
        
        # Sample from probability distribution
        next_idx = torch.multinomial(probs, 1).item()
        next_word = idx2word[next_idx]
        words_generated.append(next_word)
        
        # Slide the window (drop the first index, append new index)
        current_seq = current_seq[1:] + [next_idx]
    
    return " ".join(words_generated)

# Let's try generating with a seed of length = seq_length (3)
seed = ["hello", "world", "hello"]  # must be in vocab
generated_text = generate_text(model, seed, num_words=5)
print("Generated Text:", generated_text)

Generated Text: hello world hello pytorch hello world again pytorch


### Exercise: Experiment with the Generator
1. Change the `num_words` to 10 or 20 and see if your text generation forms any repetitive patterns.  
2. Try a **larger** dataset if you have one. Compare the coherence of the generated text.  
3. Print out intermediate hidden states if you’re curious about how the model’s representation changes over time.


In [154]:
# Suppose 'model' is our trained LSTM model, 'word2idx' and 'idx2word' are our mappings.

def generate_text_with_hidden(model, seed_words, num_words=10):
    """
    Generate text from the model, returning the hidden states as well.
    """
    model.eval()
    words_generated = seed_words[:]
    hidden_states = []   # store hidden states at each step
    
    current_seq = [word2idx[w] for w in seed_words]
    
    # Hidden and cell state, if needed
    # We'll assume 1-layer LSTM, batch_size=1
    h, c = None, None
    
    for _ in range(num_words):
        inp = torch.tensor([current_seq], dtype=torch.long)
        with torch.no_grad():
            # Modify forward pass to capture intermediate hidden states
            # We can do this by running the embedding + LSTM manually:
            embedded = model.embedding(inp)  # shape (1, seq_length, embed_dim)
            # We pass in (h, c) if they exist, otherwise let the LSTM init them
            lstm_out, (h, c) = model.lstm(embedded, (h, c) if h is not None else None)
            
            # final time step
            final_hidden = lstm_out[:, -1, :] 
            
            # For debugging: store the hidden state in a list
            hidden_states.append(final_hidden.detach().cpu().numpy())
            
            logits = model.fc(final_hidden)
            probs = torch.softmax(logits, dim=-1).squeeze()
            next_idx = torch.multinomial(probs, 1).item()
            
        next_word = idx2word[next_idx]
        words_generated.append(next_word)
        current_seq = current_seq[1:] + [next_idx]
        
    return " ".join(words_generated), hidden_states

# Example usage
seed = ["hello", "world", "hello"]
generated_text, h_states = generate_text_with_hidden(model, seed, num_words=8)
print("Generated Text:\n", generated_text)
print("Intermediate hidden states shapes:")
for i, hs in enumerate(h_states):
    print(f" Step {i+1}: {hs.shape}")


Generated Text:
 hello world hello pytorch hello world again pytorch hello world again
Intermediate hidden states shapes:
 Step 1: (1, 16)
 Step 2: (1, 16)
 Step 3: (1, 16)
 Step 4: (1, 16)
 Step 5: (1, 16)
 Step 6: (1, 16)
 Step 7: (1, 16)
 Step 8: (1, 16)


# Fun Things -- Shakespeare